### ISSUE TITLE
Can't upgrade glibc set on x32 (x32+i686+x86_64)

### ISSUE THREAD

**Issue by janekr** [poldek-pm/poldek#10]
Originally reported by qboosh <@> pld-linux.org -http://lists.pld-linux.org/mailman/pipermail/pld-devel-en/2020-April/025906.html

Why poldek ignores glibc-2.31-5.x86_64 upgrade, even when specified explicitly on command
line?

(I started with "-n th-all -Uvg glibc", then tried to add more and more
explicit package names... but in each case third arch glibc (base) package is ignored
and upgrade fails).

make-request -b th-x32 -c 'poldek -n th-all -Uvg glibc-2.31-5.x32 glibc-2.31-5.x86_64 glibc-2.31-5.i686 glibc-headers-2.31-5.x32 glibc-devel-2.31-5.x86_64 glibc-devel-2.31-5.i686 glibc-devel-2.31-5.x32 glibc-misc-2.31-5.x32'

----- Forwarded message from PLD th-x32 builder <builder-th-x32 at pld-linux.org> -----

X-Spam-Checker-Version: SpamAssassin 3.2.5 (2008-06-10) on mail.qboosh.pl
X-Spam-Level: 
X-Spam-Status: No, score=-0.0 required=5.0 tests=AWL,BAYES_00,
	DNS_FROM_AHBL_RHSBL,FH_DATE_PAST_20XX,SUBJ_ALL_CAPS autolearn=no version=3.2.5
X-Original-To: pld at qboosh.pl
X-Entity-Ref-ID: 1db2b888-15e5-40dc-8e53-43e928caf59f
From: PLD th-x32 builder <builder-th-x32 at pld-linux.org>
To: qboosh at pld-linux.org
X-PLD-Builder: th-x32
Cc: pld-logs-th at lists.pld-linux.org
Date: Sat, 25 Apr 2020 14:35:15 +0000
Subject: ERRORS: COMMAND

COMMAND (): FAILED

--- COMMAND::
Build-Time: user:12.38s sys:6.49s real:18.92s (faults io:0 non-io:1501190)

*** buildlog for COMMAND
Loading [pndir]th...
Loading [pndir]th...
Loading [pndir]th-x86_64...
Loading [pndir]th-i686...
65598 packages read
Processing dependencies...
glibc-2.31-1.i686 obsoleted by glibc-2.31-5.i686
glibc-2.31-5.i686 marks glibc-ld-2.31-5.i686 (cap glibc-ld = 6:2.31-5)
 glibc-ld-2.31-1.i686 obsoleted by glibc-ld-2.31-5.i686
glibc-2.31-1.x32 obsoleted by glibc-2.31-5.x32
glibc-devel-2.31-1.x32 obsoleted by glibc-devel-2.31-5.x32
glibc-devel-2.31-5.x32 marks glibc-devel-utils-2.31-5.x32 (cap glibc-devel-utils = 6:2.31-5)
 glibc-devel-utils-2.31-1.x32 obsoleted by glibc-devel-utils-2.31-5.x32
   greedy upgrade glibc-devel-2.31-1.x86_64 to 2.31-5.x86_64 (unresolved glibc-devel-utils = 6:2.31-1)
    glibc-devel-2.31-1.x86_64 obsoleted by glibc-devel-2.31-5.x86_64
    glibc-devel-2.31-5.x86_64 marks glibc-libcrypt-2.31-5.x86_64 (cap glibc-libcrypt(x86_64) = 6:2.31-5)
     glibc-libcrypt-2.31-1.x86_64 obsoleted by glibc-libcrypt-2.31-5.x86_64
glibc-devel-2.31-1.i686 obsoleted by glibc-devel-2.31-5.i686
  greedy upgrade glibc-static-2.31-1.x32 to 2.31-5.x32 (unresolved glibc-devel = 6:2.31-1)
   glibc-static-2.31-1.x32 obsoleted by glibc-static-2.31-5.x32
glibc-devel-2.31-5.i686 marks glibc-libcrypt-2.31-5.i686 (cap glibc-libcrypt(i686) = 6:2.31-5)
 glibc-libcrypt-2.31-1.i686 obsoleted by glibc-libcrypt-2.31-5.i686
glibc-devel-2.31-5.x32 marks glibc-libcrypt-2.31-5.x32 (cap glibc-libcrypt(x32) = 6:2.31-5)
 glibc-libcrypt-2.31-1.x32 obsoleted by glibc-libcrypt-2.31-5.x32
glibc-headers-2.31-1.x32 obsoleted by glibc-headers-2.31-5.x32
glibc-misc-2.31-1.x32 obsoleted by glibc-misc-2.31-5.x32
There are 13 packages to install (7 marked by dependencies), 13 to remove:
U glibc-2.31.(1 => 5).i686  glibc-2.31.(1 => 5).x32  
U glibc-devel-2.31.(1 => 5).i686  glibc-devel-2.31.(1 => 5).x32  
U glibc-devel-utils-2.31.(1 => 5).x32  
U glibc-headers-2.31.(1 => 5).x32  glibc-ld-2.31.(1 => 5).i686  
U glibc-libcrypt-2.31.(1 => 5).i686  
U glibc-libcrypt-2.31.(1 => 5).x32  glibc-misc-2.31.(1 => 5).x32  
U glibc-static-2.31.(1 => 5).x32
A glibc-devel-2.31-5.x86_64  glibc-libcrypt-2.31-5.x86_64
This operation will use 1.6KB of disk space.
Need to get 8.3MB of archives. 
Executing pm-command.sh --upgrade -vh --root / --define _check_dirname_deps 1...
Preparing...                ##################################################
error: Install/Erase problems:
	file /usr/share/doc/glibc-2.31/NEWS.gz from install of glibc-2.31-5.i686 conflicts with file from package glibc-2.31-1.x86_64
	file /usr/share/doc/glibc-2.31/NEWS.gz from install of glibc-2.31-5.x32 conflicts with file from package glibc-2.31-1.x86_64
Begin-PLD-Builder-Info
Build-Time: user:12.38s sys:6.49s real:18.92s (faults io:0 non-io:1501190)

End-PLD-Builder-Info

----- End forwarded message -----

Additional data

[root@naiad-pld ~]# rpm -q poldek
poldek-0.42.2-2.x32

I can provide poldek cache and /var/lib/rpm/Packages from the affected system if needed.

**Comment by arekm** [comment]
POLDEK_TRACE=1:

http://buildlogs.pld-linux.org//index.php?dist=th&arch=x32&ok=0&ns=&cnt=50&off=0&name=command&id=f3476bf8-6219-4867-9bf6-7298c4cff2ce&action=text

**Comment by mistoo** [comment]
`/var/lib/rpm/Packages`  would be helpful - please send it to me.

**Comment by janekr** [comment]
Sent via mail:

https://drive.google.com/file/d/1yBe1EXsMgf2Voa8wVsoXM7RdUoB14whx/view?usp=sharing

**Comment by mistoo** [comment]
> POLDEK_TRACE=1:

Looks like glibc-*.x86_64 is just excluded from transaction for some reason. Locally I get all 3 archs included:

```
:i3_pre_ts_install() start
:  - added   glibc-2.31-5.i686
:  - added   glibc-2.31-5.x32
:  - added   glibc-2.31-5.x86_64
:  - added   glibc-headers-2.31-5.x32
:  - added   glibc-devel-2.31-5.x86_64
:  - added   glibc-devel-2.31-5.x32
:  - added   glibc-devel-2.31-5.i686
:  - added   glibc-misc-2.31-5.x32
```

- Have you logs of `podek -Uvg glibc` call maybe?
- Can you check trace logs of `poldek -uvt glibc-2.31-5.x86_64`?

**Comment by arekm** [comment]
POLDEK_TRACE=1 poldek -n th-all -uvt glibc-2.31-5.x86_64:

http://buildlogs.pld-linux.org//index.php?dist=th&arch=x32&ok=1&name=command&id=a70b56df-fb6e-4991-967a-b28e6f3797bf&action=tail
