### ISSUE TITLE
Segfault in uninstall

### ISSUE THREAD

**Issue by rkd77** [poldek-pm/poldek#9]
cześć,
poldek

Witaj w poldkowym trybie interaktywnym. Wpisz "help" aby otrzymać pomoc.

poldek:/all-avail> uninstall (TAB-TAB) Something wrong, something not quite right.
poldek 0.42.2 (stable); die: n_hash_insert: key 'gpg-pubkey#7fac5991-45f06f46#src:1472180521' already in table

Przerwane (zrzut pamięci)

Z obcych pakietów mam zainstalowane tylko chrome i kilka zbudowanych ręcznie rpmów. rpm --rebuilddb nie pomaga

Nieinteraktywny poldek --uninstall odinstalowuje bez błędów.

**Comment by mistoo** [comment]
I cannot reproduce this. Could you please give me your poldek's cache directory ($HOME/.cache/poldek usually) and /var/lib/rpm/Packages file?

**Comment by mistoo** [comment]
Fixed; as a workaround remove duplicates of gpg-pubkey-7fac5991-45f06f46:

```
$ rpm -qa | grep gpg-pubkey-7fac5991-45f06f46 | wc -l

189

```
